=== michelleenos/pixel-sketches/sketch-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "sketch-shema",
    "title": "Sketch Schema",
    "description": "A schema for defining a sketch",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "useP5": {
            "type": "boolean"
        },
        "created": {
            "type": "string",
            "format": "yyyy-mm-dd"
        },
        "lastUpdated": {
            "type": "string",
            "format": "yyyy-mm-dd"
        },
        "description": {
            "type": "string"
        }
    }
}

=== michelleenos/pixel-sketches/sketches/004-petal-curves/sketch.json
{
    "$schema": "../../sketch-schema.json",
    "title": "petal curves",
    "created": "2023-04",
    "lastUpdated": "2026",
    "useP5": false,
    "description": "<p>Many bezier curves are drawn, making a petal shape. The control points move along a <a href='https://en.wikipedia.org/wiki/Lissajous_curve' target='_blank'>lissajous curve</a>; the parameters of this can be adjusted with the controls.</p><p>Adjusting fps will adapt to the frame rate of your machine and ensure that `fps` number of lines are drawn per second.</p>"
}

=== michelleenos/pixel-sketches/sketches/012-flow-curves-2/sketch.json
{
    "$schema": "../../sketch-schema.json",
    "title": "flow curves",
    "useP5": false,
    "created": "2026",
    "description": "<p>More experiments with curving around flow fields. This one uses a custom algorithm which takes in 4 customizable vals, which you can adjust in the controls. Points of each curve are collected in a <a href='https://available-anaconda-10d.notion.site/That-Creative-Code-Page-c5550ef2f7574126bdc77b09ed76651b?p=eb9ede010dd4422ba78221aacdafe54a&pm=c' target='_blank'>quad tree</a> for optimization purposes; still, depending on the parameters, the process can take awhile, so the algorithm runs offscreen in a web worker.</p>"
}

=== michelleenos/pixel-sketches/sketches/009-flow-steps/sketch.json
{
    "$schema": "../../sketch-schema.json",
    "title": "flow field steps",
    "useP5": true,
    "created": "2026",
    "description": "<p>Perlin noise flow field. Moving particles draw lines, layered on top of one another. The timer values essentially control the <code>z</code> input to the perlin noise function, which jumps by a certain number every <code>timeJumpInterval</code> ms.</p>"
}

=== michelleenos/pixel-sketches/sketches/010-flow-curves/sketch.json
{
    "$schema": "../../sketch-schema.json",
    "title": "flow curves",
    "useP5": false,
    "created": "2026",
    "description": "<p>Another flow field implementation, this one including checks to avoid collisions between lines. Points of each curve are collected in a <a href='https://available-anaconda-10d.notion.site/That-Creative-Code-Page-c5550ef2f7574126bdc77b09ed76651b?p=eb9ede010dd4422ba78221aacdafe54a&pm=c' target='_blank'>quad tree</a> for optimization purposes; still, depending on the parameters, the process can take awhile, so the algorithm runs offscreen in a web worker.</p>"
}
